import { Geist, Geist_Mono, Roboto_Condensed } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "DIRECT DIVERSE INFO.TECH",
  description: "Generated by create next app",
  icons: {
    icon: 'ddi.jpg', 
  },
};

const roboto = Roboto_Condensed({subsets: ['latin']});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        {children}
      </body>
    </html>
  );
}
